
CREATE TABLE DEPARTMENT (
    Dept_Num VARCHAR2(10) PRIMARY KEY,
    Dept_Name VARCHAR2(50) NOT NULL,
    Head_id VARCHAR2(10),
    Location VARCHAR2(100)
);

CREATE TABLE ACADEMIC_STAFF (
    Staff_id VARCHAR2(10) PRIMARY KEY,
    F_Name VARCHAR2(30) NOT NULL,
    L_Name VARCHAR2(30) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Dept_Num VARCHAR2(10)
);

CREATE TABLE STUDENT (
    Stu_id VARCHAR2(10) PRIMARY KEY,
    F_name VARCHAR2(30) NOT NULL,
    L_name VARCHAR2(30) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Major VARCHAR2(50)
);

CREATE TABLE COURSE (
    Course_id VARCHAR2(10) PRIMARY KEY,
    Course_Name VARCHAR2(100) NOT NULL,
    Credit_Hour NUMBER(1) NOT NULL,
    Dept_Num VARCHAR2(10)
);

CREATE TABLE LAB (
    Lab_id VARCHAR2(10) PRIMARY KEY,
    Location VARCHAR2(100),
    Capacity NUMBER(3) NOT NULL,
    Schedule_time VARCHAR2(50)
);

CREATE TABLE SECTION (
    Section_id VARCHAR2(10) PRIMARY KEY,
    Course_id VARCHAR2(10) NOT NULL,
    Instructor_id VARCHAR2(10),
    Lab_id VARCHAR2(10),
    Schedule_time VARCHAR2(50),
    Capacity NUMBER(3) NOT NULL
);

CREATE TABLE PREREQUISITE_FOR (
    Course_id VARCHAR2(10),
    Prerequisite_id VARCHAR2(10),
    PRIMARY KEY (Course_id, Prerequisite_id)
);

CREATE TABLE HAS (
    Course_id VARCHAR2(10),
    Section_id VARCHAR2(10),
    PRIMARY KEY (Course_id, Section_id)
);

ALTER TABLE ACADEMIC_STAFF
ADD CONSTRAINT fk_staff_department
FOREIGN KEY (Dept_Num) REFERENCES DEPARTMENT(Dept_Num);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT fk_department_head
FOREIGN KEY (Head_id) REFERENCES ACADEMIC_STAFF(Staff_id);

ALTER TABLE COURSE
ADD CONSTRAINT fk_course_department
FOREIGN KEY (Dept_Num) REFERENCES DEPARTMENT(Dept_Num);

ALTER TABLE SECTION
ADD CONSTRAINT fk_section_course
FOREIGN KEY (Course_id) REFERENCES COURSE(Course_id);

ALTER TABLE SECTION
ADD CONSTRAINT fk_section_instructor
FOREIGN KEY (Instructor_id) REFERENCES ACADEMIC_STAFF(Staff_id);

ALTER TABLE SECTION
ADD CONSTRAINT fk_section_lab
FOREIGN KEY (Lab_id) REFERENCES LAB(Lab_id);

ALTER TABLE PREREQUISITE_FOR
ADD CONSTRAINT fk_prereq_course
FOREIGN KEY (Course_id) REFERENCES COURSE(Course_id);

ALTER TABLE PREREQUISITE_FOR
ADD CONSTRAINT fk_prereq_prerequisite
FOREIGN KEY (Prerequisite_id) REFERENCES COURSE(Course_id);

ALTER TABLE HAS
ADD CONSTRAINT fk_has_course
FOREIGN KEY (Course_id) REFERENCES COURSE(Course_id);

ALTER TABLE HAS
ADD CONSTRAINT fk_has_section
FOREIGN KEY (Section_id) REFERENCES SECTION(Section_id);